blog/views/articles.py
from typing import Dict

import requests
from flask import Blueprint, current_app, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound

from blog.configs import BaseConfig
from blog.extension import db
from blog.forms.article import CreateArticleForm
from blog.models import Article, Author, Tag

article_app = Blueprint("article_app", __name__, url_prefix="/articles", static_folder="../static")


@article_app.route("/")
def article_list():
    articles = Article.query.all()
    count_articles: Dict = requests.get("https://flask-blog-rqp4.onrender.com/api/articles/event_get_count/").json()
    return render_template(
        "articles/list.html", articles=articles, count_articles=count_articles["count"], active="articles"
    )


@article_app.route("/<int:pk>")
def get_article(pk: int):
    _article = Article.query.filter_by(id=pk).options(joinedload(Article.tags)).one_or_none()
    if _article is None:
        raise NotFound
    return render_template("articles/detail.html", article=_article, active="articles")


@article_app.route("/create/", methods=["GET", "POST"])
@login_required
def create_article():
    error = None
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), body=form.body.data)

        if current_user.author:
            # use existing author if present
            _article.author_id = current_user.id
        else:
            # otherwise create author record
            author = Author(user_id=current_user.id)
            _article.author_id = current_user.id
            db.session.add(author)
            db.session.flush()
        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)
        db.session.add(_article)
        db.session.commit()
        return redirect(url_for("article_app.get_article", pk=_article.id))
    return render_template("articles/create.html", form=form, error=error)

blog/views/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from blog.extension import db
from blog.forms.user import LoginForm, UserRegisterForm
from blog.models import User

auth = Blueprint("auth", __name__, static_folder="../static")


@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("users_app.user_details", user_id=current_user.id))

    form = LoginForm(request.form)
    errors = []
    if request.method == "POST" and form.validate():
        email = request.form.get("email")
        password = request.form.get("password")
        user = User.query.filter_by(email=email).first()
        if not user or not check_password_hash(user.password, password):
            flash("Check your login details")
            return redirect(url_for(".login"))
        login_user(user)
        return redirect(url_for("users_app.user_details", user_id=user.id))
    return render_template(
        "auth/login.html",
        form=form,
        errors=errors,
    )


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for(".login"))

blog/views/authors.py
import requests
from flask import Blueprint, render_template

from blog.models import Author

authors_app = Blueprint("authors_app", __name__, url_prefix="/authors", static_folder="../static")


@authors_app.route("/")
def authors_list():
    authors = Author.query.all()
    article_count = {}
    for author in authors:
        article_count[author.id] = requests.get(
            f"https://flask-blog-rqp4.onrender.com/api/authors/{author.id}/event_get_articles_count/"
        ).json()
    return render_template("authors/list.html", article_count=article_count, authors=authors)

blog/views/users.py
from flask import Blueprint, current_app, redirect, render_template, request, url_for
from flask_login import current_user, login_user
from sqlalchemy.exc import IntegrityError
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from blog.extension import db
from blog.forms.user import UserRegisterForm
from blog.models import User

users_app = Blueprint("users_app", __name__, url_prefix="/users", static_folder="../static")


@users_app.route("/")
def users_list():
    users = User.query.all()
    return render_template("users/list.html", users=users)


@users_app.route("/<int:user_id>/")
def user_details(user_id: int):
    user = User.query.filter_by(id=user_id).one_or_none()
    if user is None:
        raise NotFound(f"User #{user_id} doesn't exist!")
    return render_template("users/detail.html", user=user)


@users_app.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("users_app.user_details", user_id=current_user.id))

    form = UserRegisterForm(request.form)
    errors = []

    if form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists")
            return render_template("users/register.html", form=form)

        user = User(
            email=form.email.data,
            username=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            password=generate_password_hash(form.password.data),
            is_staff=False,
        )

        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create user!")
            form.email.errors.append("Could not create user!")
        else:
            current_app.logger.info("Created user %s", user)
            login_user(user)
            return redirect(url_for("users_app.user_details", user_id=current_user.id))

    return render_template(
        "users/register.html",
        form=form,
        errors=errors,
    )

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block css %}
        <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet" >
    {% endblock %}
  </head>
  <body>
    <div class="container">
    {% include 'navbar.html' %}
    {% block body %}{% endblock %}
    </div>
    {% block js %}
        <script src="{{ url_for('static',filename='js/bootstrap.bundle.min.js') }}"></script>
    {% endblock %}
  </body>
</html>

blog/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index Page
{% endblock %}


{% block body %}
    <h1>Main page:</h1>
<h1>
Hello,
{% if current_user.is_authenticated %}
    {{ current_user.username }}
{% else %}
    anon
{% endif %}
!
</h1>

{% endblock body %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Main</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if active=='users' %}active{%endif %}" aria-current="page" href="{{ url_for('users_app.users_list')}}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if active=='authors' %}active{%endif %}" aria-current="page" href="{{ url_for('authors_app.authors_list')}}">Authors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if active=='articles' %}active{%endif %}" href="{{ url_for('article_app.article_list')}}">Articles</a>
        </li>
      <li class="nav-item">
        {% if current_user.is_authenticated %}
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            {% else %}
            <a href="{{ url_for('auth.login') }}"
            class="nav-link {% if request.endpoint == 'login' -%}active{%- endif %}">
            Login
            </a>
        {% endif %}
      </li>
      </ul>
    </div>
  </div>
</nav>